# Pcsx2Utils.cmake — iOS stub
# Replaces the full PCSX2 cmake utils for the iOS build.
# All macros are no-ops or minimal implementations sufficient for iOS/Xcode.

macro(check_no_parenthesis_in_path)
    # No-op: path check not needed for iOS CI builds
endmacro()

macro(detect_operating_system)
    set(LINUX FALSE)
    set(FREEBSD FALSE)
    set(Windows FALSE)
    set(OSX FALSE)
    if(WIN32)
        set(Windows TRUE)
    elseif(APPLE)
        set(OSX TRUE)
    endif()
endmacro()

macro(detect_compiler)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(USE_CLANG TRUE)
        set(USE_GCC FALSE)
        set(USE_MSVC FALSE)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(USE_GCC TRUE)
        set(USE_CLANG FALSE)
        set(USE_MSVC FALSE)
    elseif(MSVC)
        set(USE_MSVC TRUE)
        set(USE_CLANG FALSE)
        set(USE_GCC FALSE)
    else()
        set(USE_CLANG TRUE)
        set(USE_GCC FALSE)
        set(USE_MSVC FALSE)
    endif()
    set(IS_SUPPORTED_COMPILER TRUE)
endmacro()

function(get_git_version_info)
    # No-op: git version handled directly in top-level CMakeLists.txt
endfunction()

function(write_svnrev_h)
    # Create a minimal svnrev.h so common/ headers compile
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/common/include")
    file(WRITE "${CMAKE_BINARY_DIR}/common/include/svnrev.h"
"// Auto-generated by Pcsx2Utils.cmake iOS stub\n"
"#pragma once\n"
"#define SVN_REV_UNKNOWN 1\n"
"#define SVN_REV 0\n"
"#define SVN_MODS 0\n"
"#define GIT_TAG_STRING \"iPSX2-dev\"\n"
    )
endfunction()

macro(fixup_file_properties target)
    # No-op: precompiled header fixup not needed on Xcode/iOS
endmacro()

macro(setup_main_executable target)
    # No-op: main executable setup is done inline in top-level CMakeLists.txt for iOS
endmacro()
