# Pcsx2Utils.cmake — iOS stub
# Replaces the full PCSX2 cmake utils for the iOS build.
# All macros are no-ops or minimal implementations sufficient for iOS/Xcode.

macro(check_no_parenthesis_in_path)
    # No-op: path check not needed for iOS CI builds
endmacro()

macro(detect_operating_system)
    set(LINUX FALSE)
    set(FREEBSD FALSE)
    set(Windows FALSE)
    set(OSX FALSE)
    if(WIN32)
        set(Windows TRUE)
    elseif(APPLE)
        set(OSX TRUE)
    endif()
endmacro()

macro(detect_compiler)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(USE_CLANG TRUE)
        set(USE_GCC FALSE)
        set(USE_MSVC FALSE)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(USE_GCC TRUE)
        set(USE_CLANG FALSE)
        set(USE_MSVC FALSE)
    elseif(MSVC)
        set(USE_MSVC TRUE)
        set(USE_CLANG FALSE)
        set(USE_GCC FALSE)
    else()
        set(USE_CLANG TRUE)
        set(USE_GCC FALSE)
        set(USE_MSVC FALSE)
    endif()
    set(IS_SUPPORTED_COMPILER TRUE)
endmacro()

function(get_git_version_info)
    # No-op: git version handled directly in top-level CMakeLists.txt
endfunction()

function(write_svnrev_h)
    # Create a minimal svnrev.h so common/ headers compile
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/common/include")
    file(WRITE "${CMAKE_BINARY_DIR}/common/include/svnrev.h"
"// Auto-generated by Pcsx2Utils.cmake iOS stub\n"
"#pragma once\n"
"#define SVN_REV_UNKNOWN 1\n"
"#define SVN_REV 0\n"
"#define SVN_MODS 0\n"
"#define GIT_TAG_STRING \"iPSX2-dev\"\n"
    )
endfunction()

macro(fixup_file_properties target)
    # No-op: precompiled header fixup not needed on Xcode/iOS
endmacro()

macro(setup_main_executable target)
    # No-op: main executable setup is done inline in top-level CMakeLists.txt for iOS
endmacro()

# force_include_last — forces a header to be included last in all source files
# Used by pcsx2/CMakeLists.txt for precompiled header injection.
# On iOS/Xcode the PCH is handled automatically; this is a no-op.
function(force_include_last target header)
    # No-op for iOS/Xcode builds — Xcode manages PCH automatically.
    # On other platforms this would be: target_compile_options(${target} PRIVATE -include "${header}")
endfunction()

# target_sources_conditional — adds sources conditionally based on a flag
# Some PCSX2 CMakeLists.txt versions use this helper.
macro(target_sources_conditional target flag)
    if(${flag})
        target_sources(${target} PRIVATE ${ARGN})
    endif()
endmacro()

# pcsx2_target_compile_options — wrapper used by some PCSX2 cmake files
function(pcsx2_target_compile_options target)
    target_compile_options(${target} PRIVATE ${ARGN})
endfunction()

# source_groups_from_vcxproj_filters — reads a .vcxproj.filters file and
# creates source_group() entries for IDE organization.
# For iOS/Xcode builds this is purely cosmetic — no-op.
function(source_groups_from_vcxproj_filters filters_file)
    # No-op for iOS: Xcode organizes files by filesystem structure automatically.
    # On Windows/MSVC this would parse the XML and call source_group() for each filter.
endfunction()
